"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AccountShell } from "@/components/account/AccountShell";
import { LoadingSkeleton } from "@/components/ui/LoadingSkeleton";
import { useRouteGuard } from "@/hooks/useRouteGuard";
import { getSellerStudio, getStudioStorefront, saveStudioStorefront, updateSellerStoreIdentity, uploadStorefrontImage } from "@/services/studioStorefrontService";
import { defaultStudioStorefront, type StudioStoreCollection, type StudioStorefrontConfig } from "@/types/studio-storefront";

export function SellerStorefrontCustomizer(): React.JSX.Element {
  const auth = useRouteGuard({ allowedRoles: ["seller", "founder", "superAdmin"], requireStudioId: true });
  const studioId = auth.claims?.studioId ?? "";
  const [value, setValue] = useState<StudioStorefrontConfig>(defaultStudioStorefront(""));
  const [identity, setIdentity] = useState({ name: "", description: "", logoUrl: null as string | null, bannerUrl: null as string | null, slug: "" });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const [draggedSection, setDraggedSection] = useState<number | null>(null);
  const storePath = identity.slug ? `/studio/${identity.slug}` : "";
  const storeUrl = useMemo(() => typeof window === "undefined" || !storePath ? storePath : `${window.location.origin}${storePath}`, [storePath]);
  useEffect(() => { if (!studioId || !auth.user) return; setLoading(true); void Promise.all([getSellerStudio(studioId), getStudioStorefront(studioId, auth.user.uid)]).then(([studio, storefront]) => { if (!studio) throw new Error("Studio profile not found."); const stored=window.localStorage.getItem(`sidra-storefront-draft-${studioId}`); if(stored){try{const draft=JSON.parse(stored) as {value?:StudioStorefrontConfig;identity?:typeof identity};setIdentity(draft.identity??{ name: studio.name, description: studio.description ?? "", logoUrl: studio.logoUrl, bannerUrl: studio.bannerUrl, slug: studio.slug });setValue(draft.value??storefront);setMessage("Unsaved storefront draft restored on this device.");return;}catch{window.localStorage.removeItem(`sidra-storefront-draft-${studioId}`);}} setIdentity({ name: studio.name, description: studio.description ?? "", logoUrl: studio.logoUrl, bannerUrl: studio.bannerUrl, slug: studio.slug }); setValue(storefront); }).catch((caught) => setMessage(caught instanceof Error ? caught.message : "Storefront could not be loaded.")).finally(() => setLoading(false)); }, [auth.user, studioId]);
  useEffect(()=>{if(!studioId||loading)return;window.localStorage.setItem(`sidra-storefront-draft-${studioId}`,JSON.stringify({value,identity}));},[identity,loading,studioId,value]);
  const updateCollection = (id: string, patch: Partial<StudioStoreCollection>) => setValue((current) => ({ ...current, collections: current.collections.map((item) => item.id === id ? { ...item, ...patch } : item) }));
  const addCollection = () => setValue((current) => ({ ...current, collections: [...current.collections, { id: crypto.randomUUID(), name: "New collection", description: "", enabled: true, sortOrder: current.collections.length }] }));
  if (auth.loading || !auth.user || !studioId || loading) return <LoadingSkeleton count={8} />;
  return <AccountShell mode="seller" eyebrow="No-code Studio builder" title="Customize your store"><div className="grid gap-7 xl:grid-cols-[minmax(0,1fr)_minmax(320px,.72fr)]"><div className="grid gap-6">
    <section className="rounded-[var(--radius-lg)] border border-border bg-card p-5 sm:p-7"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[var(--color-gold-600)]">Your public store</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input readOnly value={storeUrl} className="min-w-0 flex-1 rounded-2xl border border-border bg-background px-4 py-3 text-sm" /><button type="button" onClick={() => void navigator.clipboard.writeText(storeUrl).then(() => setMessage("Store link copied."))} className="rounded-2xl border border-border px-5 py-3 text-sm font-semibold">Copy URL</button>{storePath ? <Link target="_blank" href={storePath} className="rounded-2xl bg-[var(--color-deep-plum)] px-5 py-3 text-center text-sm font-semibold text-white">Open store</Link> : null}</div></section>
    <section className="grid gap-5 rounded-[var(--radius-lg)] border border-border bg-card p-5 sm:p-7"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[var(--color-gold-600)]">Identity</p><h2 className="mt-2 font-heading text-3xl">Name, story and artwork</h2></div><label className="grid gap-2 text-sm">Studio name<input value={identity.name} onChange={(e) => setIdentity({ ...identity, name: e.target.value })} className="rounded-2xl border border-border bg-background px-4 py-3" /></label><label className="grid gap-2 text-sm">Studio story<textarea value={identity.description} onChange={(e) => setIdentity({ ...identity, description: e.target.value })} className="min-h-36 rounded-2xl border border-border bg-background px-4 py-3" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm">Logo image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={async (e) => { const file=e.target.files?.[0]; if (!file) return; setIdentity({ ...identity, logoUrl: await uploadStorefrontImage(studioId,file,"logo") }); setMessage("Logo ready. Save to publish."); }} /></label><label className="grid gap-2 text-sm">Banner image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={async (e) => { const file=e.target.files?.[0]; if (!file) return; setIdentity({ ...identity, bannerUrl: await uploadStorefrontImage(studioId,file,"banner") }); setMessage("Banner ready. Save to publish."); }} /></label></div><label className="grid gap-2 text-sm">Announcement<input value={value.announcement} maxLength={180} onChange={(e) => setValue({ ...value, announcement: e.target.value })} className="rounded-2xl border border-border bg-background px-4 py-3" /></label><label className="grid gap-2 text-sm">Store headline<input value={value.headline} maxLength={140} onChange={(e) => setValue({ ...value, headline: e.target.value })} className="rounded-2xl border border-border bg-background px-4 py-3" /></label></section>
    <section className="grid gap-5 rounded-[var(--radius-lg)] border border-border bg-card p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[var(--color-gold-600)]">Collections</p><h2 className="mt-2 font-heading text-3xl">Organize your products</h2></div><button type="button" onClick={addCollection} className="rounded-full bg-[var(--color-deep-plum)] px-5 py-3 text-sm font-semibold text-white">+ Add collection</button></div>{value.collections.length===0?<p className="rounded-2xl border border-dashed border-border p-5 text-sm text-muted">Add a collection, then select it while listing a product.</p>:null}{value.collections.map((item,index)=><div key={item.id} className="grid gap-3 rounded-2xl border border-border bg-background p-4"><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><input value={item.name} onChange={(e)=>updateCollection(item.id,{name:e.target.value})} className="rounded-xl border border-border bg-card px-4 py-3 font-semibold"/><button type="button" onClick={()=>setValue({...value,collections:value.collections.filter((x)=>x.id!==item.id)})} className="rounded-xl border border-red-200 px-4 py-2 text-sm text-red-700">Remove</button></div><textarea value={item.description} onChange={(e)=>updateCollection(item.id,{description:e.target.value})} className="min-h-20 rounded-xl border border-border bg-card px-4 py-3 text-sm"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={item.enabled} onChange={(e)=>updateCollection(item.id,{enabled:e.target.checked})}/> Show collection <span className="ml-auto text-xs text-muted">#{index+1}</span></label></div>)}</section>
    <section className="grid gap-5 rounded-[var(--radius-lg)] border border-border bg-card p-5 sm:p-7"><h2 className="font-heading text-3xl">Appearance & motion</h2><div className="grid gap-4 sm:grid-cols-4"><label className="grid gap-2 text-sm">Layout<select value={value.layout} onChange={(e)=>setValue({...value,layout:e.target.value as StudioStorefrontConfig["layout"]})} className="rounded-2xl border border-border bg-background px-4 py-3"><option value="editorial">Editorial</option><option value="gallery">Gallery</option><option value="catalog">Catalog</option></select></label><label className="grid gap-2 text-sm">Hero alignment<select value={value.heroAlignment} onChange={(e)=>setValue({...value,heroAlignment:e.target.value as StudioStorefrontConfig["heroAlignment"]})} className="rounded-2xl border border-border bg-background px-4 py-3"><option value="left">Left</option><option value="center">Center</option></select></label><label className="grid gap-2 text-sm">Motion<select value={value.motion} onChange={(e)=>setValue({...value,motion:e.target.value as StudioStorefrontConfig["motion"]})} className="rounded-2xl border border-border bg-background px-4 py-3"><option value="subtle">Subtle luxury</option><option value="cinematic">Cinematic</option><option value="still">No animation</option></select></label><label className="grid gap-2 text-sm">Accent color<input type="color" value={value.accentColor} onChange={(e)=>setValue({...value,accentColor:e.target.value})} className="h-12 w-full rounded-2xl border border-border p-1"/></label></div><div className="grid gap-3 sm:grid-cols-3">{[["showStory","Show story"],["showCollections","Show collections"],["showPolicies","Show policies"]].map(([key,label])=><label key={key} className="flex items-center gap-2 rounded-2xl border border-border px-4 py-3 text-sm"><input type="checkbox" checked={value[key as "showStory"|"showCollections"|"showPolicies"]} onChange={(e)=>setValue({...value,[key]:e.target.checked})}/>{label}</label>)}</div><div><p className="mb-3 text-sm font-semibold">Drag storefront sections into order</p><div className="grid gap-2">{value.sectionOrder.map((section,index)=><button type="button" draggable key={section} onDragStart={()=>setDraggedSection(index)} onDragOver={(event)=>event.preventDefault()} onDrop={()=>{if(draggedSection===null||draggedSection===index)return;const next=[...value.sectionOrder];const [moved]=next.splice(draggedSection,1);next.splice(index,0,moved);setValue({...value,sectionOrder:next});setDraggedSection(null);}} className="flex cursor-grab items-center justify-between rounded-xl border border-border bg-background px-4 py-3 text-left text-sm font-semibold"><span>⋮⋮ {section}</span><span className="text-muted">{index+1}</span></button>)}</div></div></section>
    {message?<p className="rounded-2xl border border-border bg-card p-4 text-sm">{message}</p>:null}<button type="button" disabled={saving} onClick={async()=>{setSaving(true);setMessage(null);try{await updateSellerStoreIdentity(studioId,identity);await saveStudioStorefront({...value,studioId,sellerUid:auth.user!.uid});window.localStorage.removeItem(`sidra-storefront-draft-${studioId}`);setMessage("Storefront saved and published.");}catch(caught){setMessage(caught instanceof Error?caught.message:"Storefront could not be saved.");}finally{setSaving(false);}}} className="rounded-full bg-[var(--color-deep-plum)] px-7 py-4 font-semibold text-white">{saving?"Publishing…":"Save & publish store"}</button>
  </div><aside className="xl:sticky xl:top-24 xl:self-start"><div className="overflow-hidden rounded-[2rem] border border-border bg-card shadow-xl" style={{borderColor:value.accentColor}}><div className="h-52 bg-[#2d1729]" style={identity.bannerUrl?{backgroundImage:`url(${identity.bannerUrl})`,backgroundPosition:"center",backgroundSize:"cover"}:undefined}/><div className={value.heroAlignment==="center"?"p-7 text-center":"p-7"}><p className="text-xs font-semibold uppercase tracking-[.2em]" style={{color:value.accentColor}}>{value.announcement||"Studio preview"}</p><h2 className="mt-3 font-heading text-4xl">{identity.name||"Your Studio"}</h2><p className="mt-3 text-sm text-muted">{value.headline}</p></div></div></aside></div></AccountShell>;
}
